[package]
name = "chapter-73-systems"
version = "0.4.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>", "Duncan McGreggor <duncan@cnbb.games>"]
license = "MIT"
repository = "https://github.com/hexagram30/client"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.7.0", features = ["serde"] }
specs = { version = "0.16.1", features = ["serde"] }
specs-derive = "0.4.0"
serde= { version = "^1.0.44", features = ["derive"] }
serde_json = "^1.0.44"
lazy_static = "1.4.0"
regex = "1.3.1"
