game:
    title: Roguelike Tutorial

logging:
    colored: true
    file: ""
    level: debug
    report_caller: true

npcs:
    count: 8
    chr: ☺
    fg_color: [0,255,0]
    bg_color: [0,0,0]
    init_x: 7
    init_y: 20

player:
    chr: "@"
    fg_color: [255,255,0]
    bg_color: [0,0,0]
