name: explore2-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Exploration 2
      run: cd explore2 && cargo build
    - name: Run Exploration 2 Tests
      run: cd explore2 && cargo test
